// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6OXyVs8VA_-WsYn-D9NMXp_PxGWT_bik',
    appId: '1:103997864822:web:697f7794e4a286c57d5857',
    messagingSenderId: '103997864822',
    projectId: 'cityyanta-376f2',
    authDomain: 'cityyanta-376f2.firebaseapp.com',
    storageBucket: 'cityyanta-376f2.firebasestorage.app',
    measurementId: 'G-083GLHD4ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJspNPk0QwDF0aBU-WCz6F5M5NIBLvhlY',
    appId: '1:103997864822:android:a93e2a90938062b17d5857',
    messagingSenderId: '103997864822',
    projectId: 'cityyanta-376f2',
    storageBucket: 'cityyanta-376f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0o_e31mHgK1M4jOBqBc95qIrIr3XmPgo',
    appId: '1:103997864822:ios:57284dfc3bc903d07d5857',
    messagingSenderId: '103997864822',
    projectId: 'cityyanta-376f2',
    storageBucket: 'cityyanta-376f2.firebasestorage.app',
    iosClientId:
        '103997864822-83c19j5581drleg9h00uvnvtg45tqsi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.setupfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0o_e31mHgK1M4jOBqBc95qIrIr3XmPgo',
    appId: '1:103997864822:ios:57284dfc3bc903d07d5857',
    messagingSenderId: '103997864822',
    projectId: 'cityyanta-376f2',
    storageBucket: 'cityyanta-376f2.firebasestorage.app',
    iosClientId:
        '103997864822-83c19j5581drleg9h00uvnvtg45tqsi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.setupfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6OXyVs8VA_-WsYn-D9NMXp_PxGWT_bik',
    appId: '1:103997864822:web:2ad0187188f7198d7d5857',
    messagingSenderId: '103997864822',
    projectId: 'cityyanta-376f2',
    authDomain: 'cityyanta-376f2.firebaseapp.com',
    storageBucket: 'cityyanta-376f2.firebasestorage.app',
    measurementId: 'G-4ZPRDKXCDY',
  );
}
